name: CI
on: [push]
jobs:
      build:
        runs-on: macOS-latest

        steps:
        - name: Checkout
          uses: actions/checkout@master
        - name: CocoaPod Install
          run: pod install
      #- name: Testing....
      # run: ls /Applications | grep Xcode
        - name: iPhone 11 Test
          run: xcodebuild test -scheme ScreenSaver -workspace ScreenSaver.xcworkspace -destination 'platform=iOS Simulator,name=iPhone 11,OS=13.1'
