name: CI

on: 
  push:
    branches:
      - master

jobs:
  build:

    runs-on: sourav's MacBook Pro
    
    steps:
    - uses: actions/checkout@master
    - name: Start xcodebuild test
      run: xcodebuild clean test -project ScreenSaver.xcodeproj -scheme ScreenSaver -destination "platform=iOS Simulator,name=iPhone 11 Pro"
